---
object_type: namespace
version: 1.0
object:
  attributes:
    name: VM
    description: 
    display_name: 
    priority: 
    enabled: 
    ancestry: 40000000000155/40000000000157
    relative_path: Infrastructure/VM
