---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
    relative_path: PhysicalInfrastructure/CiscoIntersight/Services/DeployServerProfileTemplate/Default
  fields: []
