---
object_type: method
version: 1.0
object:
  attributes:
    name: ovirt_PreProvision_Clone_to_VM
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
    relative_path: Infrastructure/VM/Provisioning/StateMachines/Methods/ovirt_PreProvision_Clone_to_VM
  inputs: []
