---
object_type: namespace
version: 1.0
object:
  attributes:
    name: StateMachines
    description: 
    display_name: 
    priority: 
    enabled: 
    ancestry: 40000000000155/40000000000157/40000000000158/40000000000159
    relative_path: Infrastructure/VM/Provisioning/StateMachines
